-- supabase/migrations/0020_label_configs_seed.sql
-- GENERATED by scripts/gen-label-seed.mjs — do not hand-edit; re-run the script.
--
-- Seeds a DRAFT label_config for every catalog product/variant (96 labels),
-- so the entire catalog is covered in the Label Studio. Mirrors the studio's
-- "Seed missing drafts" action and the seedFieldsForVariant rules:
--   * name / quantity / SKU / barcode from the live catalog
--   * blend COMPONENT NAMES from catalog data with EMPTY quantities
--     (render "pending administrative input" until the owner fills them)
--   * storage UNVERIFIED (safe placeholder prints until confirmed)
--   * lot / MFG / EXP BLANK (owner enters real batch data; nothing fabricated)
--   * default direction Core Black (switch per label in the studio)
--   * unique crypto Crockford-base32 verification code per label
--
-- Idempotent: inserts ONLY where the product+variant has no config yet — safe
-- to run alongside labels you already created by hand or via the Seed button.
-- Requires migration 0018 (label_configs).

insert into public.label_configs
  (product_id, variant_id, template_id, default_preset, status,
   display_name, quantity_label, material_type, composition,
   sku, barcode_value, verification_code, storage_source_verified, recalled)
select s.* from (values
  ('bpc-157', 'bpc-157-5mg', 'noir-clinical-core', 'full_wrap', 'draft', 'BPC-157', '5 mg', 'Lyophilized Research Material', null, 'BPC157-5', 'BPC157-5', 'ADSVZG1PVS6SQ', false, false),
  ('bpc-157', 'bpc-157-10mg', 'noir-clinical-core', 'full_wrap', 'draft', 'BPC-157', '10 mg', 'Lyophilized Research Material', null, 'BPC157-10', 'BPC157-10', '6QTX1JZH2TK7A', false, false),
  ('tb-500', 'tb-500-5mg', 'noir-clinical-core', 'full_wrap', 'draft', 'TB-500 (Thymosin β4)', '5 mg', 'Lyophilized Research Material', null, 'TB500-5', 'TB500-5', 'TPXNYC9DBBWXB', false, false),
  ('tb-500', 'tb-500-10mg', 'noir-clinical-core', 'full_wrap', 'draft', 'TB-500 (Thymosin β4)', '10 mg', 'Lyophilized Research Material', null, 'TB500-10', 'TB500-10', '5BH7X8YRCPVD1', false, false),
  ('bpc-157-tb-500', 'bpc-157-tb-500-10mg', 'noir-clinical-core', 'full_wrap', 'draft', 'BPC-157 + TB-500 Blend', '10 mg (5/5)', 'Research Blend', '[{"name":"BPC-157","quantity":""},{"name":"TB-500","quantity":""}]'::jsonb, 'BPC157TB500-10', 'BPC157TB500-10', 'Q71D625JSYE05', false, false),
  ('bpc-157-tb-500', 'bpc-157-tb-500-20mg', 'noir-clinical-core', 'full_wrap', 'draft', 'BPC-157 + TB-500 Blend', '20 mg (10/10)', 'Research Blend', '[{"name":"BPC-157","quantity":""},{"name":"TB-500","quantity":""}]'::jsonb, 'BPC157TB500-20', 'BPC157TB500-20', 'TM9SMRAFJY932', false, false),
  ('kpv', 'kpv-5mg', 'noir-clinical-core', 'full_wrap', 'draft', 'KPV', '5 mg', 'Lyophilized Research Material', null, 'KPV-5', 'KPV-5', 'XRDK777T92DXX', false, false),
  ('kpv', 'kpv-10mg', 'noir-clinical-core', 'full_wrap', 'draft', 'KPV', '10 mg', 'Lyophilized Research Material', null, 'KPV-10', 'KPV-10', 'D4Q2ZFAGSBNTZ', false, false),
  ('mgf', 'mgf-2mg', 'noir-clinical-core', 'full_wrap', 'draft', 'MGF', '2 mg', 'Lyophilized Research Material', null, 'MGF-2', 'MGF-2', 'BT28W19X08GST', false, false),
  ('ara-290', 'ara-290-10mg', 'noir-clinical-core', 'full_wrap', 'draft', 'ARA-290', '10 mg', 'Lyophilized Research Material', null, 'ARA290-10', 'ARA290-10', 'Q9DDMB4X9DR6D', false, false),
  ('ghk-cu', 'ghk-cu-50mg', 'noir-clinical-core', 'full_wrap', 'draft', 'GHK-Cu', '50 mg', 'Lyophilized Research Material', null, 'GHKCU-50', 'GHKCU-50', 'PSM88TX8RF67V', false, false),
  ('ghk-cu', 'ghk-cu-100mg', 'noir-clinical-core', 'full_wrap', 'draft', 'GHK-Cu', '100 mg', 'Lyophilized Research Material', null, 'GHKCU-100', 'GHKCU-100', '979MKYJAGKE7Q', false, false),
  ('ahk-cu', 'ahk-cu-20mg', 'noir-clinical-core', 'full_wrap', 'draft', 'AHK-Cu', '20 mg', 'Lyophilized Research Material', null, 'AHKCU-20', 'AHKCU-20', '151EB8A7PAJ81', false, false),
  ('ahk-cu', 'ahk-cu-60mg', 'noir-clinical-core', 'full_wrap', 'draft', 'AHK-Cu', '60 mg', 'Lyophilized Research Material', null, 'AHKCU-60', 'AHKCU-60', 'PFAYT109JRC7H', false, false),
  ('epitalon', 'epitalon-10mg', 'noir-clinical-core', 'full_wrap', 'draft', 'Epitalon', '10 mg', 'Lyophilized Research Material', null, 'EPITALON-10', 'EPITALON-10', 'HDGPCX8B46YM1', false, false),
  ('epitalon', 'epitalon-50mg', 'noir-clinical-core', 'full_wrap', 'draft', 'Epitalon', '50 mg', 'Lyophilized Research Material', null, 'EPITALON-50', 'EPITALON-50', 'BRXZA029CVK7D', false, false),
  ('mots-c', 'mots-c-10mg', 'noir-clinical-core', 'full_wrap', 'draft', 'MOTS-c', '10 mg', 'Lyophilized Research Material', null, 'MOTSC-10', 'MOTSC-10', '8D8ZJBX9B2W3T', false, false),
  ('mots-c', 'mots-c-20mg', 'noir-clinical-core', 'full_wrap', 'draft', 'MOTS-c', '20 mg', 'Lyophilized Research Material', null, 'MOTSC-20', 'MOTSC-20', 'QKKGCXV5Q1T8X', false, false),
  ('mots-c', 'mots-c-40mg', 'noir-clinical-core', 'full_wrap', 'draft', 'MOTS-c', '40 mg', 'Lyophilized Research Material', null, 'MOTSC-40', 'MOTSC-40', '0DRF9SSNQ56A1', false, false),
  ('ss-31', 'ss-31-10mg', 'noir-clinical-core', 'full_wrap', 'draft', 'SS-31', '10 mg', 'Lyophilized Research Material', null, 'SS31-10', 'SS31-10', 'QDDNHG6S8QVGJ', false, false),
  ('ss-31', 'ss-31-50mg', 'noir-clinical-core', 'full_wrap', 'draft', 'SS-31', '50 mg', 'Lyophilized Research Material', null, 'SS31-50', 'SS31-50', 'ZBM0T28PFK4M9', false, false),
  ('nad-plus', 'nad-plus-500mg', 'noir-clinical-core', 'full_wrap', 'draft', 'NAD+', '500 mg', 'Lyophilized Research Material', null, 'NADPLUS-500', 'NADPLUS-500', 'MNW4WTTGYM1EM', false, false),
  ('nad-plus', 'nad-plus-1000mg', 'noir-clinical-core', 'full_wrap', 'draft', 'NAD+', '1000 mg', 'Lyophilized Research Material', null, 'NADPLUS-1000', 'NADPLUS-1000', '93WX5H331BJZT', false, false),
  ('5-amino-1mq', '5-amino-1mq-5mg', 'noir-clinical-core', 'full_wrap', 'draft', '5-Amino-1MQ', '5 mg', 'Lyophilized Research Material', null, '5AMINO1MQ-5', '5AMINO1MQ-5', 'MTKWPKENVT402', false, false),
  ('5-amino-1mq', '5-amino-1mq-10mg', 'noir-clinical-core', 'full_wrap', 'draft', '5-Amino-1MQ', '10 mg', 'Lyophilized Research Material', null, '5AMINO1MQ-10', '5AMINO1MQ-10', 'V14K0F1W2GFQZ', false, false),
  ('5-amino-1mq', '5-amino-1mq-50mg', 'noir-clinical-core', 'full_wrap', 'draft', '5-Amino-1MQ', '50 mg', 'Lyophilized Research Material', null, '5AMINO1MQ-50', '5AMINO1MQ-50', 'VXZ4J0HBD01QH', false, false),
  ('aod-9604', 'aod-9604-5mg', 'noir-clinical-core', 'full_wrap', 'draft', 'AOD-9604', '5 mg', 'Lyophilized Research Material', null, 'AOD9604-5', 'AOD9604-5', '97DXZ9TSDSH3S', false, false),
  ('aod-9604', 'aod-9604-10mg', 'noir-clinical-core', 'full_wrap', 'draft', 'AOD-9604', '10 mg', 'Lyophilized Research Material', null, 'AOD9604-10', 'AOD9604-10', 'F0BC9SZZ0ME3M', false, false),
  ('glutathione', 'glutathione-600mg', 'noir-clinical-core', 'full_wrap', 'draft', 'Glutathione', '600 mg', 'Lyophilized Research Material', null, 'GLUTATHIONE-600', 'GLUTATHIONE-600', 'KTJ6GQ0RZ7MJF', false, false),
  ('glutathione', 'glutathione-1200mg', 'noir-clinical-core', 'full_wrap', 'draft', 'Glutathione', '1200 mg', 'Lyophilized Research Material', null, 'GLUTATHIONE-1200', 'GLUTATHIONE-1200', '8XT1MPBTCYVJA', false, false),
  ('semax', 'semax-5mg', 'noir-clinical-core', 'full_wrap', 'draft', 'Semax', '5 mg', 'Lyophilized Research Material', null, 'SEMAX-5', 'SEMAX-5', 'E1S8NJJ3QJP9H', false, false),
  ('semax', 'semax-10mg', 'noir-clinical-core', 'full_wrap', 'draft', 'Semax', '10 mg', 'Lyophilized Research Material', null, 'SEMAX-10', 'SEMAX-10', 'WY35RYZQP0SQ9', false, false),
  ('selank', 'selank-5mg', 'noir-clinical-core', 'full_wrap', 'draft', 'Selank', '5 mg', 'Lyophilized Research Material', null, 'SELANK-5', 'SELANK-5', 'CWP2066JZSQG5', false, false),
  ('selank', 'selank-10mg', 'noir-clinical-core', 'full_wrap', 'draft', 'Selank', '10 mg', 'Lyophilized Research Material', null, 'SELANK-10', 'SELANK-10', 'SF6M801ZCKC8F', false, false),
  ('selank-semax', 'selank-semax-20mg', 'noir-clinical-core', 'full_wrap', 'draft', 'Selank + Semax Blend', '20 mg (10/10)', 'Research Blend', '[{"name":"Selank","quantity":""},{"name":"Semax","quantity":""}]'::jsonb, 'SELANKSEMAX-20', 'SELANKSEMAX-20', 'H45ZB4MF40CX6', false, false),
  ('snap-8', 'snap-8-10mg', 'noir-clinical-core', 'full_wrap', 'draft', 'Snap-8', '10 mg', 'Lyophilized Research Material', null, 'SNAP8-10', 'SNAP8-10', 'XH0CT9RMV4XMB', false, false),
  ('dsip', 'dsip-5mg', 'noir-clinical-core', 'full_wrap', 'draft', 'DSIP', '5 mg', 'Lyophilized Research Material', null, 'DSIP-5', 'DSIP-5', 'QECQ4NWJ188Y5', false, false),
  ('dsip', 'dsip-10mg', 'noir-clinical-core', 'full_wrap', 'draft', 'DSIP', '10 mg', 'Lyophilized Research Material', null, 'DSIP-10', 'DSIP-10', 'A43VE9QXQ3JM8', false, false),
  ('vip', 'vip-5mg', 'noir-clinical-core', 'full_wrap', 'draft', 'VIP', '5 mg', 'Lyophilized Research Material', null, 'VIP-5', 'VIP-5', '1GB9YS25R8BBS', false, false),
  ('vip', 'vip-10mg', 'noir-clinical-core', 'full_wrap', 'draft', 'VIP', '10 mg', 'Lyophilized Research Material', null, 'VIP-10', 'VIP-10', 'E27Z3HQ0FPW7M', false, false),
  ('p21', 'p21-5mg', 'noir-clinical-core', 'full_wrap', 'draft', 'P21', '5 mg', 'Lyophilized Research Material', null, 'P21-5', 'P21-5', 'K5HFQ19JDCSFJ', false, false),
  ('sermorelin', 'sermorelin-5mg', 'noir-clinical-core', 'full_wrap', 'draft', 'Sermorelin', '5 mg', 'Lyophilized Research Material', null, 'SERMORELIN-5', 'SERMORELIN-5', 'YRD6PT8C20HDS', false, false),
  ('sermorelin', 'sermorelin-10mg', 'noir-clinical-core', 'full_wrap', 'draft', 'Sermorelin', '10 mg', 'Lyophilized Research Material', null, 'SERMORELIN-10', 'SERMORELIN-10', '1RDMEB64MGQZ4', false, false),
  ('cjc-1295-no-dac', 'cjc-1295-no-dac-5mg', 'noir-clinical-core', 'full_wrap', 'draft', 'CJC-1295 (no DAC)', '5 mg', 'Lyophilized Research Material', null, 'CJC1295NODAC-5', 'CJC1295NODAC-5', '4448W2NBVHYJ3', false, false),
  ('cjc-1295-no-dac', 'cjc-1295-no-dac-10mg', 'noir-clinical-core', 'full_wrap', 'draft', 'CJC-1295 (no DAC)', '10 mg', 'Lyophilized Research Material', null, 'CJC1295NODAC-10', 'CJC1295NODAC-10', 'PSPC1RTB47RGA', false, false),
  ('cjc-1295-ipamorelin', 'cjc-1295-ipamorelin-10mg', 'noir-clinical-core', 'full_wrap', 'draft', 'CJC-1295 + Ipamorelin Blend', '10 mg (5/5)', 'Research Blend', '[{"name":"CJC-1295","quantity":""},{"name":"Ipamorelin","quantity":""}]'::jsonb, 'CJC1295IPAMORELIN-10', 'CJC1295IPAMORELIN-10', 'R6SH7GHQNW4ZR', false, false),
  ('ipamorelin', 'ipamorelin-5mg', 'noir-clinical-core', 'full_wrap', 'draft', 'Ipamorelin', '5 mg', 'Lyophilized Research Material', null, 'IPAMORELIN-5', 'IPAMORELIN-5', 'X489R35W0K43M', false, false),
  ('ipamorelin', 'ipamorelin-10mg', 'noir-clinical-core', 'full_wrap', 'draft', 'Ipamorelin', '10 mg', 'Lyophilized Research Material', null, 'IPAMORELIN-10', 'IPAMORELIN-10', 'FQVBDA3M8HN7G', false, false),
  ('ghrp-2', 'ghrp-2-5mg', 'noir-clinical-core', 'full_wrap', 'draft', 'GHRP-2', '5 mg', 'Lyophilized Research Material', null, 'GHRP2-5', 'GHRP2-5', 'NC87QT1FB73Q1', false, false),
  ('ghrp-2', 'ghrp-2-10mg', 'noir-clinical-core', 'full_wrap', 'draft', 'GHRP-2', '10 mg', 'Lyophilized Research Material', null, 'GHRP2-10', 'GHRP2-10', 'WS9K04X2Q2NA8', false, false),
  ('ghrp-6', 'ghrp-6-5mg', 'noir-clinical-core', 'full_wrap', 'draft', 'GHRP-6', '5 mg', 'Lyophilized Research Material', null, 'GHRP6-5', 'GHRP6-5', 'TPN6T802032F9', false, false),
  ('ghrp-6', 'ghrp-6-10mg', 'noir-clinical-core', 'full_wrap', 'draft', 'GHRP-6', '10 mg', 'Lyophilized Research Material', null, 'GHRP6-10', 'GHRP6-10', 'KXEQ3AR0GZXBA', false, false),
  ('hexarelin', 'hexarelin-2mg', 'noir-clinical-core', 'full_wrap', 'draft', 'Hexarelin', '2 mg', 'Lyophilized Research Material', null, 'HEXARELIN-2', 'HEXARELIN-2', '52NEPVP2G6DAY', false, false),
  ('hexarelin', 'hexarelin-5mg', 'noir-clinical-core', 'full_wrap', 'draft', 'Hexarelin', '5 mg', 'Lyophilized Research Material', null, 'HEXARELIN-5', 'HEXARELIN-5', 'CM5WVF8EYDEGS', false, false),
  ('tesamorelin', 'tesamorelin-5mg', 'noir-clinical-core', 'full_wrap', 'draft', 'Tesamorelin', '5 mg', 'Lyophilized Research Material', null, 'TESAMORELIN-5', 'TESAMORELIN-5', 'VMAEECXRN672J', false, false),
  ('tesamorelin', 'tesamorelin-10mg', 'noir-clinical-core', 'full_wrap', 'draft', 'Tesamorelin', '10 mg', 'Lyophilized Research Material', null, 'TESAMORELIN-10', 'TESAMORELIN-10', '26GV0EDEHBKMH', false, false),
  ('tesamorelin', 'tesamorelin-20mg', 'noir-clinical-core', 'full_wrap', 'draft', 'Tesamorelin', '20 mg', 'Lyophilized Research Material', null, 'TESAMORELIN-20', 'TESAMORELIN-20', 'BQ7Q6GNR3TM5Z', false, false),
  ('mk-677', 'mk-677-5mg', 'noir-clinical-core', 'full_wrap', 'draft', 'MK-677 (Ibutamoren)', '5 mg', 'Lyophilized Research Material', null, 'MK677-5', 'MK677-5', '9Z1WSZY4VD96X', false, false),
  ('igf1-lr3', 'igf1-lr3-1mg', 'noir-clinical-core', 'full_wrap', 'draft', 'IGF1-LR3', '1 mg', 'Lyophilized Research Material', null, 'IG1', 'IG1', 'DMGRMVF1FKR1Q', false, false),
  ('thymosin-alpha-1', 'thymosin-alpha-1-5mg', 'noir-clinical-core', 'full_wrap', 'draft', 'Thymosin Alpha-1', '5 mg', 'Lyophilized Research Material', null, 'THYMOSINALPHA1-5', 'THYMOSINALPHA1-5', 'A6Y3T6NXTGQC1', false, false),
  ('thymosin-alpha-1', 'thymosin-alpha-1-10mg', 'noir-clinical-core', 'full_wrap', 'draft', 'Thymosin Alpha-1', '10 mg', 'Lyophilized Research Material', null, 'THYMOSINALPHA1-10', 'THYMOSINALPHA1-10', '7TP9D3KTBAP1C', false, false),
  ('thymalin', 'thymalin-10mg', 'noir-clinical-core', 'full_wrap', 'draft', 'Thymalin', '10 mg', 'Lyophilized Research Material', null, 'THYMALIN-10', 'THYMALIN-10', 'F170WYXB937DW', false, false),
  ('ll-37', 'll-37-10mg', 'noir-clinical-core', 'full_wrap', 'draft', 'LL-37', '10 mg', 'Lyophilized Research Material', null, 'LL37-10', 'LL37-10', 'HQCCNQNP8V6Q3', false, false),
  ('kisspeptin-10', 'kisspeptin-10-5mg', 'noir-clinical-core', 'full_wrap', 'draft', 'Kisspeptin-10', '5 mg', 'Lyophilized Research Material', null, 'KISSPEPTIN10-5', 'KISSPEPTIN10-5', 'HXBC06ZQMAGFE', false, false),
  ('kisspeptin-10', 'kisspeptin-10-10mg', 'noir-clinical-core', 'full_wrap', 'draft', 'Kisspeptin-10', '10 mg', 'Lyophilized Research Material', null, 'KISSPEPTIN10-10', 'KISSPEPTIN10-10', 'JRG7QH9AQJBTG', false, false),
  ('glow', 'glow-70mg', 'noir-clinical-core', 'full_wrap', 'draft', 'GLOW Blend', '70 mg', 'Research Blend', '[{"name":"GHK-Cu","quantity":""},{"name":"BPC-157","quantity":""},{"name":"TB-500","quantity":""}]'::jsonb, 'GLOW-70', 'GLOW-70', 'QVJZNF7G202JN', false, false),
  ('klow', 'klow-80mg', 'noir-clinical-core', 'full_wrap', 'draft', 'KLOW Blend', '80 mg', 'Research Blend', '[{"name":"GHK-Cu","quantity":""},{"name":"BPC-157","quantity":""},{"name":"TB-500","quantity":""},{"name":"KPV","quantity":""}]'::jsonb, 'KLOW-80', 'KLOW-80', 'YTE5WTAH1FMVA', false, false),
  ('tirzepatide', 'tirzepatide-5mg', 'noir-clinical-core', 'full_wrap', 'draft', 'Tirzepatide', '5 mg', 'Lyophilized Research Material', null, 'TR5', 'TR5', '3WDQYQB8D5N5P', false, false),
  ('tirzepatide', 'tirzepatide-10mg', 'noir-clinical-core', 'full_wrap', 'draft', 'Tirzepatide', '10 mg', 'Lyophilized Research Material', null, 'TR10', 'TR10', 'MXG2QJT9KMWMG', false, false),
  ('tirzepatide', 'tirzepatide-15mg', 'noir-clinical-core', 'full_wrap', 'draft', 'Tirzepatide', '15 mg', 'Lyophilized Research Material', null, 'TR15', 'TR15', 'CCMHQJ0C5EHS7', false, false),
  ('tirzepatide', 'tirzepatide-20mg', 'noir-clinical-core', 'full_wrap', 'draft', 'Tirzepatide', '20 mg', 'Lyophilized Research Material', null, 'TR20', 'TR20', 'M68K1GA1HV7F7', false, false),
  ('tirzepatide', 'tirzepatide-30mg', 'noir-clinical-core', 'full_wrap', 'draft', 'Tirzepatide', '30 mg', 'Lyophilized Research Material', null, 'TR30', 'TR30', '2PMGRNZGQ9R4T', false, false),
  ('tirzepatide', 'tirzepatide-40mg', 'noir-clinical-core', 'full_wrap', 'draft', 'Tirzepatide', '40 mg', 'Lyophilized Research Material', null, 'TR40', 'TR40', 'EBN3TQ7RCF2XZ', false, false),
  ('tirzepatide', 'tirzepatide-50mg', 'noir-clinical-core', 'full_wrap', 'draft', 'Tirzepatide', '50 mg', 'Lyophilized Research Material', null, 'TR50', 'TR50', '23Y3BN19PPCCK', false, false),
  ('tirzepatide', 'tirzepatide-60mg', 'noir-clinical-core', 'full_wrap', 'draft', 'Tirzepatide', '60 mg', 'Lyophilized Research Material', null, 'TR60', 'TR60', 'J4SGB28KAEJFW', false, false),
  ('tirzepatide', 'tirzepatide-100mg', 'noir-clinical-core', 'full_wrap', 'draft', 'Tirzepatide', '100 mg', 'Lyophilized Research Material', null, 'TR100', 'TR100', 'Q2M521AV2JN1F', false, false),
  ('tirzepatide', 'tirzepatide-120mg', 'noir-clinical-core', 'full_wrap', 'draft', 'Tirzepatide', '120 mg', 'Lyophilized Research Material', null, 'TR120', 'TR120', '1BR2NXH6G9EYB', false, false),
  ('semaglutide', 'semaglutide-2mg', 'noir-clinical-core', 'full_wrap', 'draft', 'Semaglutide', '2 mg', 'Lyophilized Research Material', null, 'SM2', 'SM2', 'WKCE34WS06ZC4', false, false),
  ('semaglutide', 'semaglutide-5mg', 'noir-clinical-core', 'full_wrap', 'draft', 'Semaglutide', '5 mg', 'Lyophilized Research Material', null, 'SM5', 'SM5', '43H6902WRVNV9', false, false),
  ('semaglutide', 'semaglutide-10mg', 'noir-clinical-core', 'full_wrap', 'draft', 'Semaglutide', '10 mg', 'Lyophilized Research Material', null, 'SM10', 'SM10', '2D9PZXCVW1WFR', false, false),
  ('semaglutide', 'semaglutide-15mg', 'noir-clinical-core', 'full_wrap', 'draft', 'Semaglutide', '15 mg', 'Lyophilized Research Material', null, 'SM15', 'SM15', '2STC9V8JHCCT2', false, false),
  ('semaglutide', 'semaglutide-20mg', 'noir-clinical-core', 'full_wrap', 'draft', 'Semaglutide', '20 mg', 'Lyophilized Research Material', null, 'SM20', 'SM20', 'BAFT9JDJN51K4', false, false),
  ('semaglutide', 'semaglutide-30mg', 'noir-clinical-core', 'full_wrap', 'draft', 'Semaglutide', '30 mg', 'Lyophilized Research Material', null, 'SM30', 'SM30', 'D80WJPR53W2MK', false, false),
  ('semaglutide', 'semaglutide-40mg', 'noir-clinical-core', 'full_wrap', 'draft', 'Semaglutide', '40 mg', 'Lyophilized Research Material', null, 'SM40', 'SM40', '6ZEA28V7FF6J2', false, false),
  ('retatrutide', 'retatrutide-5mg', 'noir-clinical-core', 'full_wrap', 'draft', 'Retatrutide', '5 mg', 'Lyophilized Research Material', null, 'RT5', 'RT5', '2KZE10RJ714VA', false, false),
  ('retatrutide', 'retatrutide-10mg', 'noir-clinical-core', 'full_wrap', 'draft', 'Retatrutide', '10 mg', 'Lyophilized Research Material', null, 'RT10', 'RT10', 'WN8X8A9N7A20M', false, false),
  ('retatrutide', 'retatrutide-15mg', 'noir-clinical-core', 'full_wrap', 'draft', 'Retatrutide', '15 mg', 'Lyophilized Research Material', null, 'RT15', 'RT15', 'BESFYS4466R0M', false, false),
  ('retatrutide', 'retatrutide-20mg', 'noir-clinical-core', 'full_wrap', 'draft', 'Retatrutide', '20 mg', 'Lyophilized Research Material', null, 'RT20', 'RT20', 'DCN81XMVZ8N8D', false, false),
  ('retatrutide', 'retatrutide-30mg', 'noir-clinical-core', 'full_wrap', 'draft', 'Retatrutide', '30 mg', 'Lyophilized Research Material', null, 'RT30', 'RT30', 'J9SSGH3BX1MS2', false, false),
  ('retatrutide', 'retatrutide-40mg', 'noir-clinical-core', 'full_wrap', 'draft', 'Retatrutide', '40 mg', 'Lyophilized Research Material', null, 'RT40', 'RT40', 'Z2F0J9PX2ZDTE', false, false),
  ('retatrutide', 'retatrutide-50mg', 'noir-clinical-core', 'full_wrap', 'draft', 'Retatrutide', '50 mg', 'Lyophilized Research Material', null, 'RT50', 'RT50', 'F0KFFY5PJZYW0', false, false),
  ('retatrutide', 'retatrutide-60mg', 'noir-clinical-core', 'full_wrap', 'draft', 'Retatrutide', '60 mg', 'Lyophilized Research Material', null, 'RT60', 'RT60', '3X90AEWSFAYED', false, false),
  ('survodutide', 'survodutide-10mg', 'noir-clinical-core', 'full_wrap', 'draft', 'Survodutide', '10 mg', 'Lyophilized Research Material', null, 'SUR10', 'SUR10', '32S5WBQ6GPY4N', false, false),
  ('cagrilintide', 'cagrilintide-5mg', 'noir-clinical-core', 'full_wrap', 'draft', 'Cagrilintide', '5 mg', 'Lyophilized Research Material', null, 'CGL5', 'CGL5', 'V5MFK0YM99J5C', false, false),
  ('cagrilintide', 'cagrilintide-10mg', 'noir-clinical-core', 'full_wrap', 'draft', 'Cagrilintide', '10 mg', 'Lyophilized Research Material', null, 'CGL10', 'CGL10', 'ZKCZ3J9DXBCTE', false, false),
  ('cagrilintide-semaglutide', 'cagrilintide-semaglutide-10mg', 'noir-clinical-core', 'full_wrap', 'draft', 'Cagrilintide + Semaglutide Blend', '10 mg', 'Research Blend', '[{"name":"Cagrilintide","quantity":""},{"name":"Semaglutide","quantity":""}]'::jsonb, 'CS10', 'CS10', 'RJNQ8GZF4E2VV', false, false)
) as s(product_id, variant_id, template_id, default_preset, status,
       display_name, quantity_label, material_type, composition,
       sku, barcode_value, verification_code, storage_source_verified, recalled)
where not exists (
  select 1 from public.label_configs lc
  where lc.product_id = s.product_id
    and lc.variant_id is not distinct from s.variant_id
);

-- Summary: 96 draft labels seeded (idempotent).
