-- 0038_product_specs.sql   (opt cycle 11 — scorecard 4.4)
-- GENERATED by scripts/gen-specs-migration.mjs from src/data/productSpecs.js —
-- do not hand-edit; re-run the script. Every value is a transcription of a
-- verified source (named in productSpecs.js); nothing is derived. UPDATE only,
-- coalesce: a value already present (entered in the Control Room) is kept.
-- Idempotent. Additive in effect (no column, no row created).

update public.products set peptide_sequence = coalesce(peptide_sequence, 'GEPPPGKPADDAGLV'), molecular_weight = coalesce(molecular_weight, '1419.53 g/mol'), cas_number = coalesce(cas_number, '137525-51-0') where id = 'bpc-157';
update public.products set peptide_sequence = coalesce(peptide_sequence, 'Tyr-D-Ala-Asp-Ala-Ile-Phe-Thr-Gln-Ser-Tyr-Arg-Lys-Val-Leu-Ala-Gln-Leu-Ser-Ala-Arg-Lys-Leu-Leu-Gln-Asp-Ile-Leu-Ser-Arg-NH2'), molecular_weight = coalesce(molecular_weight, '3367.97 g/mol') where id = 'cjc-1295-no-dac';
update public.products set peptide_sequence = coalesce(peptide_sequence, 'Aib-His-D-2-Nal-D-Phe-Lys-NH2'), molecular_weight = coalesce(molecular_weight, '711.85 g/mol'), cas_number = coalesce(cas_number, '170851-70-4') where id = 'ipamorelin';
update public.products set peptide_sequence = coalesce(peptide_sequence, 'MEHFPGP'), molecular_weight = coalesce(molecular_weight, '813.92 g/mol'), cas_number = coalesce(cas_number, '80714-61-0') where id = 'semax';
update public.products set peptide_sequence = coalesce(peptide_sequence, 'TKPRPGP'), molecular_weight = coalesce(molecular_weight, '751.91 g/mol'), cas_number = coalesce(cas_number, '129954-34-3') where id = 'selank';
update public.products set molecular_weight = coalesce(molecular_weight, '663.43 g/mol'), cas_number = coalesce(cas_number, '53-84-9') where id = 'nad-plus';
update public.products set peptide_sequence = coalesce(peptide_sequence, 'MRWQEMGYIFYPRKLR'), molecular_weight = coalesce(molecular_weight, '2174.62 g/mol'), cas_number = coalesce(cas_number, '1627580-64-6') where id = 'mots-c';
update public.products set molecular_weight = coalesce(molecular_weight, '403.93 g/mol'), cas_number = coalesce(cas_number, '89030-95-5') where id = 'ghk-cu';
update public.products set peptide_sequence = coalesce(peptide_sequence, 'AEDG'), molecular_weight = coalesce(molecular_weight, '390.35 g/mol'), cas_number = coalesce(cas_number, '307297-39-8') where id = 'epitalon';
update public.products set peptide_sequence = coalesce(peptide_sequence, 'Ac-SDAAVDTSSEITTKDLKEKKEVVEEAEN'), molecular_weight = coalesce(molecular_weight, '3108.30 g/mol'), cas_number = coalesce(cas_number, '62304-98-7') where id = 'thymosin-alpha-1';
update public.products set molecular_weight = coalesce(molecular_weight, '307.32 g/mol'), cas_number = coalesce(cas_number, '70-18-8') where id = 'glutathione';
